esphome:
  name: garage_door
  platform: ESP8266
  board: d1_mini
  includes:
    - evo-60m.h
  libraries:
    #- "Wire"

uart:
  id: uart_bus
  tx_pin: D1
  rx_pin: D2
  baud_rate: 115200

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False


sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new Evo60m(id(uart_bus));
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "${upper_devicename} height"
      unit_of_measurement: cm
      accuracy_decimals: 1
